---
title: "Integration of mIF and IMC data"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

Here, we will integrate mIF and IMC data.

## Load data

First, we will read in the `SingleCellExperiment` objects storing the IMC and 
IF data.

```{r read-data, message=FALSE}
library(SingleCellExperiment)
library(tidyverse)

sce_IF <- readRDS("/Volumes/immucan_volume/processed_data/Panel_1/2022_WORKFLOW/mIF/Rout/sce_ROIs.rds")
sce_IMC <- readRDS("/Volumes/immucan_volume/processed_data/Panel_1/2022_WORKFLOW/IMC/Rout/sce.rds")
```

## Batch integration

We will test if the `fastMNN` correction can integrate the data.

```{r fastMNN}
library(batchelor)
library(scater)
library(dittoSeq)

sce_IMC <- sce_IMC[c("CD15",  "Ecad",    "CD3",   "CD11c", "CD20",  "CD163"),]
rownames(sce_IMC) <- c("CD15",  "CK",    "CD3",   "CD11c", "CD20",  "CD163")
colData(sce_IMC) <- colData(sce_IMC)[,c("sample_id", "matched_celltype")]
colData(sce_IF) <- colData(sce_IF)[,c("sample_id", "matched_celltype")]
assays(sce_IF) <- assays(sce_IF)[c("counts", "exprs")]

reducedDims(sce_IF) <- NULL
reducedDims(sce_IMC) <- NULL

colPairs(sce_IF) <- NULL
colPairs(sce_IMC) <- NULL

sce_IF$technology <- "IF"
sce_IMC$technology <- "IMC"

sce_merged <- cbind(sce_IMC, sce_IF)

set.seed(12345)
out <- fastMNN(sce_merged, batch = sce_merged$technology, auto.merge = TRUE, correct.all = TRUE,
               assay.type = "exprs")

reducedDim(sce_merged, "corrected") <- reducedDim(out, "corrected") 

sce_merged <- runUMAP(sce_merged, dimred = "corrected")
colnames(sce_merged) <- seq_len(ncol(sce_merged))

dittoDimPlot(sce_merged, var = "technology", size = 0.5)
dittoDimPlot(sce_merged, var = "matched_celltype", size = 0.5)

dittoDimPlot(sce_merged[,sce_merged$technology == "IMC"], var = "matched_celltype", size = 0.5)
dittoDimPlot(sce_merged[,sce_merged$technology == "IF"], var = "matched_celltype", size = 0.5)
```

We can now estimate the fraction of unmatched cell types in the data.

```{r unmatched-cells, message=FALSE}
library(tidyverse)
library(pheatmap)
library(viridis)

pairs <- metadata(out)$merge.info$pairs[[1]]
pairs$left_cells <- sce_merged$matched_celltype[pairs$left]
pairs$right_cells <- sce_merged$matched_celltype[pairs$right]

matched_cells <- pairs %>% as_tibble() %>%
  group_by(left, left_cells, right_cells) %>%
  summarise(freq = n()) %>%
  arrange(desc(freq), .by_group = TRUE) %>%
  filter(row_number()==1)

for_plot <- table(matched_cells$left_cells, matched_cells$right_cells)
rownames(for_plot) <- paste("IMC", rownames(for_plot))
colnames(for_plot) <- paste("IF", colnames(for_plot))

pheatmap(log10(for_plot + 10), color = viridis(100))
```


