---
title: "Figure S3"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: inline
---

Code to generate the plots for Figure S3.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

# set path
this path should be the directory where all files downloaded from Zenodo are stored in the same structure as on Zenodo
```{r}
mount_path <- readRDS(file = "data/mount_path.rds")
output <- "output/Figure_S3/"
```

## Read data

```{r, message=FALSE}
library(SingleCellExperiment)
library(data.table)
library(tidyverse)
```



# B - signal stability
```{r}
dat <- fread(paste0(mount_path  ,"IF_fluorophore_time_series/QuPath_project/measurements.csv"),stringsAsFactors = FALSE)
```


```{r}
#subset the data table

dat_new <- dat[, .(Image, `Cell: DAPI mean`, `Cell: EGFP mean`, `Cell: Cy3 mean`, `Cell: AF647 mean`)]

dat_sum <- dat_new %>%
  group_by(Image) %>%
  summarise(mean_DAPI = mean(`Cell: DAPI mean`),
            mean_panCK = mean(`Cell: EGFP mean`), 
            mean_CD45 = mean(`Cell: Cy3 mean`),
            mean_CD163 = mean (`Cell: AF647 mean`))


#Using data.table
#test <- dat_new[, .(mean_DAPI = mean(`Cell: DAPI mean`)), by = Image]


#Extract the time and sampleID values
dat_sum <- as.data.table(dat_sum)
dat_sum <- dat_sum[, time := stringr::str_extract(string = dat_sum$Image, pattern = "[0-9]+hr")]
dat_sum <- dat_sum[, sampleID := sub(pattern = "20210923_", "", dat_sum$Image)]
dat_sum <- dat_sum[, sampleID := sub(pattern = "20210921_", "", dat_sum$sampleID)]
dat_sum <- dat_sum[, sampleID := sub(pattern = "_0hr", "", dat_sum$sampleID)]
dat_sum <- dat_sum[, sampleID := sub(pattern = "_48hr", "", dat_sum$sampleID)]



#melt the data table
dat_melt <- melt(dat_sum, 
     id.vars = c("sampleID", "time"),
     measure.vars = c("mean_DAPI", "mean_panCK", "mean_CD45", "mean_CD163"),
     variable.name = "Marker_mean",
     value.name = "value")
```

```{r, fig.height=12, fig.width=10}

#Draw a barplot
p <- ggplot(dat_melt, aes(x=Marker_mean, y = value, fill = time)) + 
  geom_bar(stat="identity", position=position_dodge())+
  scale_fill_manual(values=c('#999999','#E69F00')) +
  facet_wrap(~sampleID, scales = "free") +
  #stat_compare_means(label = "p.signif")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90,hjust=1,vjust=0.5))
p

fn <- paste0(paste("Barplots", "0hrvs48hr", sep = "_"), '.png')
ggsave (filename = "Fig_S3.pdf", plot = p, device = "pdf", path = output, width = 12, height = 8)

```
