---
title: "Figure 4"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: inline
---

Code to generate the plots of S2

```{r}
# Set path
if (Sys.info()["sysname"] == "Windows"){
  mount_path <- "O:/projects/immucan/"
} else {
  mount_path <- "/Volumes/G_DQBM_BB_Central$/projects/immucan"
}
```

## libraries

```{r, message=FALSE}
library(SingleCellExperiment)
library(tidyverse)
library(data.table)
library(cowplot)
library(imcRtools)
library(ggpubr)
```

# A - Control cell pellets

Here we will show the marker and cell type abundace changes in sections from cell pellets acquired over two years
```{r}
cyto_cyto_sce <- readRDS(paste0(mount_path,"/processed_data/Panel_1/2022_WORKFLOW/cytoblocks/Rout/Cleaned_cytoblocks_sce.rds"))

library(ggplot2)
library(tidyr)
library(dplyr)

coldata <- as.data.frame(colData(cyto_sce))

p <- ggplot(coldata, aes(x = Batch, fill = label))+
  geom_bar(position = "fill")+
  labs(y = "Proportion")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  scale_fill_manual("Labels", values = metadata(cyto_sce)$colour_vectors$cell_types)+
  facet_wrap(~Activation_status)
p 

ggsave (filename = "Fig_S2A.png", plot = p, device = "png", path = "../output/Figure_S2/", width=350, height=200, units='mm', dpi=600)
```

# B - CV for cell type detection

```{r}
# filter out undefined cells for further analysis
coldata <- coldata%>%
  filter(label != "Undefined")


p <- ggplot(coldata %>%
  group_by(Batch, Activation_status, label)%>%
  summarise(n = n()) %>%
  mutate(freq = n/sum(n)) %>%
  group_by(label,Activation_status) %>%
  summarise(CV = sd(freq)/mean(freq)),
  # aes(x = label, y = CV across Batches, col = label))+
  aes(x = label, y = CV))+
  geom_point()+
  theme_bw()+
  # scale_color_manual("Labels", values = metadata(sce)$colour_vectors$cell_types) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  facet_wrap(~Activation_status)

p 

ggsave (filename = "Fig_S2B.png", plot = p, device = "png", path = "../output/Figure_S2/", width=200, height=150, units='mm', dpi=600)
```

# C - mean expression of cell type relevant markers

```{r, fig.height=15, fig.width=10}
markers <- list()

# functional markers for T cells
markers[["CD8 T-cells (activated)"]] <- rownames(cyto_sce)[grepl(pattern = "CD27|CD45RA|CD45RO|LAG3|PD1|CD7|GrzB|ICOS|Ki67|TCF7|VISTA",rownames(cyto_sce))]
markers[["CD8 T-cells (non-activated)"]] <- rownames(cyto_sce)[grepl(pattern = "CD27|CD45RA|CD45RO|LAG3|PD1|CD7|GrzB|ICOS|Ki67|TCF7|VISTA",rownames(cyto_sce))]

markers[["T-Helper (activated)"]] <- rownames(cyto_sce)[grepl(pattern = "CD27|CD45RA|CD45RO|LAG3|PD1|CD7|GrzB|FOXP3|ICOS|Ki67|TCF7|VISTA",rownames(cyto_sce))]
markers[["T-Helper (non-activated)"]] <- rownames(cyto_sce)[grepl(pattern = "CD27|CD45RA|CD45RO|LAG3|PD1|CD7|GrzB|FOXP3|ICOS|Ki67|TCF7|VISTA",rownames(cyto_sce))]


# B and BnT cell markers
markers[["B-cells"]] <- rownames(cyto_sce)[grepl(pattern = "CD27|CD45RA|CD45RO|HLADR|CD40|CD20",rownames(cyto_sce))]

# NK markers
markers[["NK"]] <- rownames(cyto_sce)[grepl(pattern = "CD7|GrzB|CD16$|CD45RA|CD45RO",rownames(cyto_sce))]

# tumor markers
markers[["PDL-1 positive Epithelial cells"]] <- rownames(cyto_sce)[grepl(pattern = "Ecad|HLADR|CarbonicAnhydrase|cleavedPARP|PDL1|IDO1|CD15|Ki67",rownames(cyto_sce))]

markers[["Ecad positive Epithelial cells"]] <- rownames(cyto_sce)[grepl(pattern = "Ecad|HLADR|CarbonicAnhydrase|cleavedPARP|PDL1|IDO1|CD15|Ki67",rownames(cyto_sce))]

# myeloid markers
markers[["Macrophages"]] <- rownames(cyto_sce)[grepl(pattern = "CD68|CD11c|PDL1|ICOS|VISTA|CD40|CD14|CD206|IDO1|CD33|CD16|CD163",rownames(cyto_sce))]
markers[["Myeloid"]] <- rownames(cyto_sce)[grepl(pattern = "CD68|CD11c|PDL1|ICOS|VISTA|CD40|CD14|CD206|IDO1|CD33|CD16|CD163",rownames(cyto_sce))]

# Apoptotic
markers[["Apoptotic B-cells"]] <- rownames(cyto_sce)[grepl(pattern = "cleavedPARP",rownames(cyto_sce))]


# separate by activation status
cyto_sce_act <- cyto_sce[,cyto_sce$Activation_status == "activated"]
cyto_sce_non_act <- cyto_sce[,cyto_sce$Activation_status == "non-activated"]




```

## activated cells 

```{r}
# compute mean expression of marker per batch and cluster
# Activated
library(reshape2)

# extract expression matrix as dataframe and add label and batch information
expr_df_act <- as.data.frame(t(assay(cyto_sce_act, "exprs")))
expr_df_act$label <- cyto_sce_act$label
expr_df_act$Batch <- cyto_sce_act$Batch

# reshape dataframe so it fits our needs
expr_df_act <- expr_df_act %>%
  group_by(Batch,label)%>%
  summarise(across(everything(), mean),
            .groups = 'drop')

expr_df_act <- melt(expr_df_act, id.vars=c('Batch',"label"), 
                  measure.vars=rownames(cyto_sce),
                  na.rm = F)

# select for relevant markers per cell type
for (lbl in unique(expr_df_act$label)){
  expr_df_act <- expr_df_act[!((expr_df_act$label == lbl) & !(expr_df_act$variable %in% markers[[lbl]])),]
}
p <- ggplot(expr_df_act, aes(x = variable, y= value))+
  geom_jitter(aes(col = Batch)) +
  geom_boxplot(alpha = 0.2)+
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), text = element_text(size = 15))+
  scale_color_manual("Batch", values = metadata(cyto_sce)$colour_vectors$Batch) +
  facet_wrap(~label, scales = "free_x") +
  ylab("mean expression") +
  xlab("marker") +
  ggtitle("Cell type specific Variation in marker expression across Batches (activated)")

p
ggsave (filename = "Fig_S2C_activated.png", plot = p, device = "png", path = "../output/Figure_S2/", width=250, height=400, units='mm', dpi=600)

```

## non-activated cells

```{r}
# extract expression matrix as dataframe and add label and batch information
expr_df_act <- as.data.frame(t(assay(cyto_sce_non_act, "exprs")))
expr_df_act$label <- cyto_sce_non_act$label
expr_df_act$Batch <- cyto_sce_non_act$Batch

# reshape dataframe so it fits our needs
expr_df_act <- expr_df_act %>%
  group_by(Batch,label)%>%
  summarise(across(everything(), mean),
            .groups = 'drop')

expr_df_act <- melt(expr_df_act, id.vars=c('Batch',"label"), 
                  measure.vars=rownames(cyto_sce),
                  na.rm = F)

# select for relevant markers per cell type
for (lbl in unique(expr_df_act$label)){
  expr_df_act <- expr_df_act[!((expr_df_act$label == lbl) & !(expr_df_act$variable %in% markers[[lbl]])),]
}
p <- ggplot(expr_df_act, aes(x = variable, y= value))+
  geom_jitter(aes(col = Batch)) +
  geom_boxplot(alpha = 0.2)+
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), text = element_text(size = 15))+
  scale_color_manual("Batch", values = metadata(cyto_sce)$colour_vectors$Batch) +
  facet_wrap(~label, scales = "free_x") +
  ylab("mean expression") +
  xlab("marker") +
  ggtitle("Cell type specific Variation in marker expression across Batches (activated)")

p
ggsave (filename = "Fig_S2C_non_activated.png", plot = p, device = "png", path = "../output/Figure_S2/", width=250, height=400, units='mm', dpi=600)

```



# E
```{r}
dat <- fread(paste0(mount_path  ,"processed_data/Panel_1/2022_WORKFLOW/IF_fluorophore_time_series/QuPath_project/measurements.csv"))
```


```{r}
#subset the data table

dat_new <- dat[, .(Image, `Cell: DAPI mean`, `Cell: EGFP mean`, `Cell: Cy3 mean`, `Cell: AF647 mean`)]

dat_sum <- dat_new %>%
  group_by(Image) %>%
  summarise(mean_DAPI = mean(`Cell: DAPI mean`),
            mean_panCK = mean(`Cell: EGFP mean`), 
            mean_CD45 = mean(`Cell: Cy3 mean`),
            mean_CD163 = mean (`Cell: AF647 mean`))


#Using data.table
#test <- dat_new[, .(mean_DAPI = mean(`Cell: DAPI mean`)), by = Image]


#Extract the time and sampleID values
dat_sum <- as.data.table(dat_sum)
dat_sum <- dat_sum[, time := stringr::str_extract(string = dat_sum$Image, pattern = "[0-9]+hr")]
dat_sum <- dat_sum[, sampleID := sub(pattern = "20210923_", "", dat_sum$Image)]
dat_sum <- dat_sum[, sampleID := sub(pattern = "20210921_", "", dat_sum$sampleID)]
dat_sum <- dat_sum[, sampleID := sub(pattern = "_0hr", "", dat_sum$sampleID)]
dat_sum <- dat_sum[, sampleID := sub(pattern = "_48hr", "", dat_sum$sampleID)]



#melt the data table
dat_melt <- melt(dat_sum, 
     id.vars = c("sampleID", "time"),
     measure.vars = c("mean_DAPI", "mean_panCK", "mean_CD45", "mean_CD163"),
     variable.name = "Marker_mean",
     value.name = "value")


#Widen the data table
dat_test <- dcast(dat_melt, sampleID + Marker_mean ~ time, value.var = "value")

#compute the fold change
dat_test <- dat_test [, fc := (dat_test$`48hr` - dat_test$`0hr`)/dat_test$`0hr`]

```

```{r, fig.height=12, fig.width=10}

#Draw a barplot
p <- ggplot(dat_melt, aes(x=Marker_mean, y = value, fill = time)) + 
  geom_bar(stat="identity", position=position_dodge())+
  scale_fill_manual(values=c('#999999','#E69F00')) +
  facet_wrap(~sampleID, scales = "free") +
  stat_compare_means(label = "p.signif")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90,hjust=1,vjust=0.5))
p

fn <- paste0(paste("Barplots", "0hrvs48hr", sep = "_"), '.png')
ggsave (filename = "Fig_S2E.png", plot = p, device = "png", path = "../output/Figure_S2/", width=350, height=300, units='mm', dpi=600)

```

