---
title: "Figure S5"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: inline
---

Code to generate the plots of Figure S5.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

Code to generate the plots of Figure 4.

# set path
the git repo contains a vector which specifies the path to the data folder. please adapt this path in your clone to run the repo automated.
```{r}
mount_path <- readRDS(file = "data/mount_path.rds")
output <- "output/Figure_S5"
```

## Read data

```{r, message=FALSE}
library(SingleCellExperiment)
library(tidyverse)
library(ggpubr)
library(cowplot)
library(imcRtools)


sce_IMC <- readRDS(file.path(mount_path, "IMC/Rout/sce.rds"))
sce_mIF <- readRDS(file.path(mount_path, "mIF/Rout/sce_ROIs.rds"))
```

# A - Number of cells

```{r}
if (!dir.exists("output/Figure_S5/")) dir.create("output/Figure_S5/")

no_IMC <- colData(sce_IMC) %>% as_tibble() %>%
  group_by(sample_id, patient_id) %>%
  summarize(count = n())
no_mIF <- colData(sce_mIF) %>% as_tibble() %>%
  group_by(sample_id, patient_id) %>%
  summarize(count = n())

combined_df <- left_join(no_IMC, no_mIF, by = c("sample_id", "patient_id"))
combined_df$patient_id <- sub("-", "", str_extract(combined_df$sample_id, "[0-9]{8}-"))

p <- ggplot(combined_df) + 
  geom_point(aes(count.x, count.y, color = patient_id), size = 2) + 
  geom_abline(slope = 1, intercept = 0, color = "dark red") +
  geom_smooth(aes(count.x, count.y), method='lm', formula= y~x, fullrange=TRUE) + 
  theme_minimal(base_size = 20) + xlab("# Cells in IMC") + ylab("# Cells in mIF") +
  coord_fixed() + 
  ylim(c(0, 5000)) + xlim(c(0, 5000)) +
  scale_color_manual(values = metadata(sce_IMC)$color_vectors$patient_id, name = "Patient ID")

p
ggsave(filename = "FigS5_A.pdf",path = output, plot = p, width = 10, height = 7)
```

# B - cellular area

```{r}
cur_dat <- data.frame(IMC_cell_size = sce_IMC$area)

mean_IMC <- mean(cur_dat$IMC_cell_size)
mean_IF <- mean(sce_mIF$cell.area)
p <- cur_dat %>%
  ggplot(aes(y= IMC_cell_size))+
  geom_density(col= "blue", size = 2)+
  coord_flip()+
  theme_bw()+
  geom_density(data = data.frame(IF_cell_size = sce_mIF$cell.area) ,aes(y = IF_cell_size),col= "red", size = 2)+
  annotate("text", x = 0.009, y = 392 , label = expression( paste("IMC, mean = 78 µm"^2)), color = "blue", size = 5)+
  annotate("text", x = 0.01, y = 400 , label = expression( paste("mIF, mean = 149 µm"^2)), color = "red", size = 5)+
  ylab("cell size")+
  xlab("density estimate")
  #geom_hline(yintercept = mean_IMC, col= "blue")+
  #geom_hline(yintercept = mean_IF, col= "red")
p
ggsave(filename = "FigS5_B.pdf",path= output, plot = p, width = 7, height = 5)
```




# Supporting plots for DA analysis

```{r, fig.height=10, fig.width=10}
cur_mIF <- colData(sce_mIF)
cur_IMC <- colData(sce_IMC)

# Proportions of cell types for IMC
cur_IMC$matched_celltype <- factor(cur_IMC$matched_celltype)
prop_IMC <- cur_IMC %>% 
  as.data.frame() %>%
  group_by(sample_id, patient_id, matched_celltype, .drop = FALSE) %>%
  summarize(count = n()) %>%
  group_by(sample_id) %>%
  mutate(prop = count/sum(count))

# Proportions of cell types for mIF
cur_mIF$matched_celltype <- factor(cur_mIF$matched_celltype)
prop_mIF <- cur_mIF %>% 
  as.data.frame() %>%
  group_by(sample_id, patient_id, matched_celltype, .drop = FALSE) %>%
  summarize(count = n()) %>%
  group_by(sample_id) %>%
  mutate(prop = count/sum(count))

prop_IMC$modality <- "IMC"
prop_mIF$modality <- "mIF"

out <- rbind(prop_IMC, prop_mIF)

(p <- ggplot(out) + 
  geom_boxplot(aes(modality, prop), outlier.shape = NA) +
  geom_point(aes(modality, prop, color = patient_id)) +
  geom_line(aes(modality, prop, group = sample_id)) +
  facet_wrap(~matched_celltype, nrow = 1, scales = "free")  +
  theme_classic(base_size = 20) +
  ylab("Proportion of cell phenotypes") +
  xlab("Modality") +
  scale_color_manual(values = metadata(sce_IMC)$color_vectors$patient_id, "Patient ID"))
p
ggsave(filename = "FigS5_C.pdf",path=output, plot = p, height = 5, width = 17)
```

Example images

```{r, eval=FALSE}
library(cytomapper)

(p1 <- plotSpatial(sce_IMC[,sce_IMC$sample_id == "IMMUcan_2022_WFLOW_10073140-SPECT-VAR-TIS-01-IMC-01_004"], 
            img_id = "sample_id", node_color_by = "matched_celltype") +
  scale_color_manual(values = metadata(sce_IMC)$color_vectors$matched_celltype) +
    theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        panel.background = element_rect(fill = "black", colour = NA),
        legend.position = "none") + ggtitle(""))

(p2 <- plotSpatial(sce_mIF[,sce_mIF$sample_id == "IMMUcan_2022_WFLOW_10073140-SPECT-VAR-TIS-01-IMC-01_004"], 
            img_id = "sample_id", node_color_by = "matched_celltype", coords = c("nucleus.x", "nucleus.y")) +
  scale_color_manual(values = metadata(sce_IMC)$color_vectors$matched_celltype) +
    theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        panel.background = element_rect(fill = "black", colour = NA)) + ggtitle(""))

#ggsave(filename = "../output/Figure_S5/FigS5_D1.pdf", plot = p1, height = 10, width = 10)
#ggsave(filename = "../output/Figure_S5/FigS5_D2.pdf", plot = p2, height = 10, width = 10)
```
