---
title: "Figure S5"
author: "Daniel Schulz"
date: "2025-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

In this script we will only generate a figure from the analysis that was performed at Ewa Szczureks lab (here)[https://github.com/dav3794/IMC-models/blob/main/models/compare_results.ipynb]

```{r}
library(tidyverse)
library(ggplot2)
library(pals)
library(SingleCellExperiment)
```

# TPR and FPR
We will load the confusion matrices from each model and caluclate TPR and FPR and plot them as boxplots

The data can be obtained here: https://github.com/dav3794/IMC-models

```{r}
XGB <- read_tsv("D:/Git/IMC-models/models/Baselines/xgb_predictions.tsv")
RF <- read_tsv("D:/Git/IMC-models/models/Baselines/rf_predictions.tsv")
MLP <- read_tsv("D:/Git/IMC-models/models/Baselines/mlp_predictions.tsv")
LR <- read_tsv("D:/Git/IMC-models/models/Baselines/logreg_predictions.tsv")
Stellar <- read_tsv("D:/Git/IMC-models/models/Stellar/stellar_predictions_unified_columns.tsv")
Celesta <- read_csv("D:/Git/IMC-models/models/Celesta/celesta_predictions_bis_unifified_columns.txt")
Astir <- read_tsv("D:/Git/IMC-models/models/Astir/astir_predictions_unified_columns.tsv")
Astir <- Astir %>%
  mutate(predicted_label = ifelse(predicted_label == "Other","Unknown",predicted_label))
Starling <- read_tsv("D:/Git/IMC-models/models/Starling/starling_predictions.tsv")

dat <- list(XGB,RF,MLP,LR,Stellar,Celesta,Astir,Starling)
names(dat) <- c("XGB","RF","MLP","LR","Stellar","Celesta","Astir","Starling")
```

clean the data

```{r}
lapply(dat, colnames)
dat <- lapply(dat, function(x){
  x <- x[,c("predicted_label","true_label")]
  return(x)
})

# get confusion matrices
library(caret)
# here we define all possible names that the cell types have
all_levels <- unique(unlist(lapply(dat,function(x){
  x$predicted_label
})))
cms <- lapply(dat, function(x){
  cm <- confusionMatrix(data = factor(x$predicted_label, levels = all_levels), reference = factor(x$true_label, levels = all_levels), mode = "everything")
  y <- as.data.frame(cm$byClass)
  return(y)
})

library(caret)

#confusion matrix Astir
cur_dat <- confusionMatrix(data = factor(dat$Astir$predicted_label, levels = sort(all_levels)),reference = factor(dat$Astir$true_label, levels = sort(all_levels)))
cur_dat <- t(cur_dat$table)
cur_dat <- round(cur_dat/rowSums(cur_dat),digits = 2)
cur_dat <- as.data.frame(unclass(cur_dat))
cur_dat <- cur_dat %>%
  filter(!is.na(Unknown))


pdf(file = "output/Figure_S5/confusion_matrix_Astir.pdf",width = 7, height = 7)
pheatmap::pheatmap(cur_dat,color = colorRampPalette(c("white", "darkblue"))(100),display_numbers = TRUE, cluster_rows = FALSE, cluster_cols = FALSE,number_color = text_colors <- ifelse(cur_dat > 0.5, "white", "black"),main = "Astir")
dev.off()

#confusion matrix Celesta
cur_dat <- confusionMatrix(data = factor(dat$Celesta$predicted_label, levels = sort(all_levels)),reference = factor(dat$Celesta$true_label, levels = sort(all_levels)))
cur_dat <- t(cur_dat$table)
cur_dat <- round(cur_dat/rowSums(cur_dat),digits = 2)
cur_dat <- as.data.frame(unclass(cur_dat))
cur_dat <- cur_dat %>%
  filter(!is.na(Unknown))

pdf(file = "output/Figure_S5/confusion_matrix_Celesta.pdf",width = 7, height = 7)
pheatmap::pheatmap(cur_dat,color = colorRampPalette(c("white", "darkblue"))(100),display_numbers = TRUE, cluster_rows = FALSE, cluster_cols = FALSE,number_color = text_colors <- ifelse(cur_dat > 0.5, "white", "black"),main = "Celesta")
dev.off()

#confusion matrix Starling
cur_dat <- confusionMatrix(data = factor(dat$Starling$predicted_label, levels = sort(all_levels)),reference = factor(dat$Starling$true_label, levels = sort(all_levels)))
cur_dat <- t(cur_dat$table)
cur_dat <- round(cur_dat/rowSums(cur_dat),digits = 2)
cur_dat <- as.data.frame(unclass(cur_dat))
cur_dat <- cur_dat %>%
  filter(!is.na(Unknown))

pdf(file = "output/Figure_S5/confusion_matrix_Starling.pdf",width = 7, height = 7)
pheatmap::pheatmap(cur_dat,color = colorRampPalette(c("white", "darkblue"))(100),display_numbers = TRUE, cluster_rows = FALSE, cluster_cols = FALSE,number_color = text_colors <- ifelse(cur_dat > 0.5, "white", "black"),main = "Starling")
dev.off()

#confusion matrix Stellar
cur_dat <- confusionMatrix(data = factor(dat$Stellar$predicted_label, levels = sort(all_levels)),reference = factor(dat$Stellar$true_label, levels = sort(all_levels)))
cur_dat <- t(cur_dat$table)
cur_dat <- round(cur_dat/rowSums(cur_dat),digits = 2)
cur_dat <- as.data.frame(unclass(cur_dat))
cur_dat <- cur_dat %>%
  filter(!is.na(Unknown))

pdf(file = "output/Figure_S5/confusion_matrix_Stellar.pdf",width = 7, height = 7)
pheatmap::pheatmap(cur_dat,color = colorRampPalette(c("white", "darkblue"))(100),display_numbers = TRUE, cluster_rows = FALSE, cluster_cols = FALSE,number_color = text_colors <- ifelse(cur_dat > 0.5, "white", "black"),main = "Stellar")
dev.off()
```
