---
title: "Figure 4"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Code to generate the plots of Figure 4.

## Read data

```{r, message=FALSE}
library(SingleCellExperiment)
library(tidyverse)
library(ggpubr)
library(cowplot)
library(imcRtools)

mount_path <- "/Volumes/G_DQBM_BB_Central$/projects/immucan"

sce_IMC <- readRDS(file.path(mount_path, "processed_data/Panel_1/2022_WORKFLOW/IMC/Rout/sce.rds"))
sce_mIF <- readRDS(file.path(mount_path, "processed_data/Panel_1/2022_WORKFLOW/mIF/Rout/sce_ROIs.rds"))
```

# Spatial comparison

## Mergin of data

```{r prepare-data}
# Prepare mIF data
cur_mIF <- sce_mIF
colData(cur_mIF) <- colData(cur_mIF)[,c("sample_id", "patient_id", "nucleus.x", "nucleus.y", "matched_celltype", "tissue.type", "TLS.ID")]
cur_mIF$Pos_X <- cur_mIF$nucleus.x
cur_mIF$Pos_Y <- cur_mIF$nucleus.y

cur_mIF$Pos_X <- cur_mIF$Pos_X * 0.4962
cur_mIF$Pos_Y <- cur_mIF$Pos_Y * 0.4962

cur_mIF$nucleus.x <- NULL
cur_mIF$nucleus.y <- NULL

rowData(cur_mIF) <- NULL
assays(cur_mIF) <- list()
metadata(cur_mIF) <- list()

rownames(cur_mIF) <- NULL

colPairs(cur_mIF) <- NULL
cur_mIF$modality <- "mIF"

# Prepare IMC data
cur_IMC <- sce_IMC
colData(cur_IMC) <- colData(cur_IMC)[,c("sample_id", "patient_id", "matched_celltype", "Pos_X", "Pos_Y")]
cur_IMC$tissue.type <- c("stroma", "tumor")[as.numeric(sce_IMC$tumor_patches) + 1]
cur_IMC$TLS.ID <- sce_IMC$CD20_patches

rowData(cur_IMC) <- NULL
assays(cur_IMC) <- list()
metadata(cur_IMC) <- list()

rownames(cur_IMC) <- NULL
reducedDims(cur_IMC) <- NULL
colPairs(cur_IMC) <- NULL
cur_IMC$modality <- "IMC"

# Merge data
all_sce <- cbind(cur_IMC[1:6,], cur_mIF)
all_sce$sample_id_global <- paste0(all_sce$sample_id, "_", all_sce$modality)
```

## Lcross based comparison - example images

```{r Lcross}
# Good images
# Area 29258, p 0.01
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_Batch20210921_10082495-SPECT-VAR-TIS-01-IMC-01_004"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "Tumor"]

# Area 47510, p 0.01
plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10075371-SPECT-VAR-TIS-01-IMC-01_003"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "B"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

# Area 52021, p 0.01
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10073140-SPECT-VAR-TIS-01-IMC-01_002"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "BnT"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

# Area 18210, p 0.01
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10061074-SPECT-VAR-TIS-01-IMC-01_002"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "DC"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

# Area 27379, p 0.01
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10067433-SPECT-VAR-TIS-01-IMC-01_001"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "MacCD163"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

# Area 22904, p 0.01
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10068868-SPECT-VAR-TIS-01-IMC-01_005"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "other"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

# Area 32533, p 0.01
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10067433-SPECT-VAR-TIS-01-IMC-01_001"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "T"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

# Area 35468, p 0.01
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10075371-SPECT-VAR-TIS-01-IMC-01_003"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "Neutrophil"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

# Bad images

# Area 501, p 0.01
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10075371-SPECT-VAR-TIS-01-IMC-01_002"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "Tumor"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

# Area 10289, p 0.06
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10074349-SPECT-VAR-TIS-UNST-03_004"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "B"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

# Area 10895, p 0.01
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10073140-SPECT-VAR-TIS-01-IMC-01_004"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "BnT"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

# Area 2479, p 0.08
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10073140-SPECT-VAR-TIS-01-IMC-01_002"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "DC"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

# Area 1426, p 0.02
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10073140-SPECT-VAR-TIS-01-IMC-01_003"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "MacCD163"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

# Area -1096, p 0.01
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10073140-SPECT-VAR-TIS-01-IMC-01_003"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "other"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

# Area 1263, p 0.01
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10073140-SPECT-VAR-TIS-01-IMC-01_002"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "T"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

# Area -9209, p 0.01
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10071582-SPECT-VAR-TIS-01-IMC-01_005"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "Neutrophil"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)
```

# spicyR example images

```{r}
# T cells
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10067433-SPECT-VAR-TIS-01-IMC-01_002"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "T"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

# Neutrophil and other
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10075371-SPECT-VAR-TIS-01-IMC-01_002"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "Neutrophil" | cur_sce$matched_celltype == "other"]

plotSpatial(cur_sce[,cur_sce$modality == "IMC"], node_color_by = "matched_celltype", img_id = "sample_id", flip_y = TRUE)
plotSpatial(cur_sce[,cur_sce$modality == "mIF"], node_color_by = "matched_celltype", img_id = "sample_id", flip_y = TRUE)

cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10071582-SPECT-VAR-TIS-01-IMC-01_005"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "Neutrophil" | cur_sce$matched_celltype == "other"]

plotSpatial(cur_sce[,cur_sce$modality == "IMC"], node_color_by = "matched_celltype", img_id = "sample_id", flip_y = TRUE)
plotSpatial(cur_sce[,cur_sce$modality == "mIF"], node_color_by = "matched_celltype", img_id = "sample_id", flip_y = TRUE)

# MacCD163
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10071582-SPECT-VAR-TIS-01-IMC-01_006"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "MacCD163"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10074832-SPECT-VAR-TIS-01-IMC-01_002"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "MacCD163"]

plotSpatial(cur_sce, node_color_by = "modality", img_id = "sample_id", flip_y = TRUE)

# Tumor and MacCD163
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10075371-SPECT-VAR-TIS-01-IMC-01_001"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "MacCD163" | cur_sce$matched_celltype == "Tumor"]

plotSpatial(cur_sce[,cur_sce$modality == "IMC"], node_color_by = "matched_celltype", img_id = "sample_id", flip_y = TRUE)
plotSpatial(cur_sce[,cur_sce$modality == "mIF"], node_color_by = "matched_celltype", img_id = "sample_id", flip_y = TRUE)

cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10071582-SPECT-VAR-TIS-01-IMC-01_005"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "MacCD163" | cur_sce$matched_celltype == "Tumor"]

plotSpatial(cur_sce[,cur_sce$modality == "IMC"], node_color_by = "matched_celltype", img_id = "sample_id", flip_y = TRUE)
plotSpatial(cur_sce[,cur_sce$modality == "mIF"], node_color_by = "matched_celltype", img_id = "sample_id", flip_y = TRUE)

# Tumor and T
cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10071582-SPECT-VAR-TIS-01-IMC-01_007"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "T" | cur_sce$matched_celltype == "Tumor"]

plotSpatial(cur_sce[,cur_sce$modality == "IMC"], node_color_by = "matched_celltype", img_id = "sample_id", flip_y = TRUE)
plotSpatial(cur_sce[,cur_sce$modality == "mIF"], node_color_by = "matched_celltype", img_id = "sample_id", flip_y = TRUE)

cur_sce <- all_sce[,all_sce$sample_id == "IMMUcan_2022_WFLOW_10061074-SPECT-VAR-TIS-01-IMC-01_002"]
cur_sce <- cur_sce[,cur_sce$matched_celltype == "T" | cur_sce$matched_celltype == "Tumor"]

plotSpatial(cur_sce[,cur_sce$modality == "IMC"], node_color_by = "matched_celltype", img_id = "sample_id", flip_y = TRUE)
plotSpatial(cur_sce[,cur_sce$modality == "mIF"], node_color_by = "matched_celltype", img_id = "sample_id", flip_y = TRUE)
```
